"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { motion } from "motion/react";
import { ArrowLeftIcon, ArrowRightIcon, PauseIcon, PlayIcon, SpeakerHighIcon, SpeakerSlashIcon } from "@phosphor-icons/react";
import { cldPoster, cldPosterTiny, cldVideo } from "@/lib/media";

/* Poster frames are generated by Cloudinary from the video itself at
   `posterAt` seconds, so there are no stored thumbnails. */
const COMMERCIALS = [
  { id: "raindance", title: "Raindance", meta: "Dave ft. Tems, music video", posterAt: 1 },
  { id: "bts-behind-scenes", title: "Snow Bunny", meta: "Brand collab", posterAt: 1 },
  { id: "olamide-rock-me-gentle", title: "Rock Me Gentle", meta: "Olamide, music video", posterAt: 12 },
  { id: "bnxn-buju", title: "BNXN (Buju)", meta: "Music video", posterAt: 1 },
  { id: "ldm-clo", title: "LDM CLO", meta: "Commercial", posterAt: 1 },
  { id: "lia-aw22", title: "Lia Cowan", meta: "Runway show", posterAt: 1 },
  { id: "errand-ready", title: "Snow Bunny", meta: "Errand Ready", posterAt: 1 },
  { id: "meji-meji-collab", title: "Meji Meji", meta: "Commercial", posterAt: 1 },
  { id: "shine-cartel", title: "The Shine Cartel", meta: "Beauty commercial", posterAt: 1 },
  { id: "streetsouk", title: "Streetsouk", meta: "Commercial", posterAt: 1 },
].map((c) => ({
  ...c,
  src: cldVideo(`candice/commercials/${c.id}`),
  poster: cldPoster(`candice/commercials/${c.id}`, c.posterAt),
  posterTiny: cldPosterTiny(`candice/commercials/${c.id}`, c.posterAt),
}));

type Commercial = (typeof COMMERCIALS)[number];

function CtrlBtn({
  onClick,
  label,
  children,
}: {
  onClick: (e: React.MouseEvent) => void;
  label: string;
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-label={label}
      className="flex h-10 w-10 items-center justify-center bg-black/55 text-white backdrop-blur-md transition-transform active:scale-95"
    >
      {children}
    </button>
  );
}

function VideoCard({
  c,
  isPlaying,
  onToggle,
  onScrollAway,
}: {
  c: Commercial;
  isPlaying: boolean;
  onToggle: () => void;
  onScrollAway: () => void;
}) {
  const cardRef = useRef<HTMLLIElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const [muted, setMuted] = useState(false);

  // The <video> follows the isPlaying prop, so starting another card
  // pauses this one.
  useEffect(() => {
    const v = videoRef.current;
    if (!v) return;
    if (isPlaying) {
      v.muted = muted;
      v.play().catch(() => {});
    } else {
      v.pause();
    }
  }, [isPlaying, muted]);

  // Pause when the card scrolls out of view while playing.
  useEffect(() => {
    const el = cardRef.current;
    if (!el || !isPlaying) return;
    const obs = new IntersectionObserver(([entry]) => !entry.isIntersecting && onScrollAway(), {
      threshold: 0.35,
    });
    obs.observe(el);
    return () => obs.disconnect();
  }, [isPlaying, onScrollAway]);

  return (
    <li ref={cardRef} className="w-[72vw] shrink-0 snap-start sm:w-[42vw] md:w-[30vw] lg:w-84">
      <div className="group relative aspect-9/16 overflow-hidden bg-surface">
        {/* Blurred poster fills the frame when a cut is landscape */}
        <div
          aria-hidden
          className="absolute inset-0 scale-125 bg-cover bg-center blur-2xl brightness-50"
          style={{ backgroundImage: `url(${c.posterTiny})` }}
        />
        <video
          ref={videoRef}
          src={c.src}
          poster={c.poster}
          loop
          playsInline
          preload="none"
          className="absolute inset-0 h-full w-full object-contain"
        />

        {!isPlaying && (
          <button
            type="button"
            onClick={onToggle}
            aria-label={`Play ${c.title}`}
            className="absolute inset-0 flex items-center justify-center bg-black/15 text-white"
          >
            <span className="flex h-16 w-16 items-center justify-center bg-accent text-on-accent transition-transform duration-300 group-hover:scale-110">
              <PlayIcon size={26} weight="fill" />
            </span>
          </button>
        )}

        {isPlaying && (
          <div className="absolute right-3 bottom-3 flex gap-2">
            <CtrlBtn onClick={onToggle} label={`Pause ${c.title}`}>
              <PauseIcon size={18} weight="fill" />
            </CtrlBtn>
            <CtrlBtn onClick={() => setMuted((m) => !m)} label={muted ? "Unmute" : "Mute"}>
              {muted ? <SpeakerSlashIcon size={18} /> : <SpeakerHighIcon size={18} />}
            </CtrlBtn>
          </div>
        )}
      </div>
      <p className="mt-3 text-base font-medium md:text-lg">{c.title}</p>
      <p className="text-sm text-ink-dim">{c.meta}</p>
    </li>
  );
}

export default function Commercials() {
  const [playing, setPlaying] = useState<string | null>(null);
  const railRef = useRef<HTMLUListElement>(null);
  const stop = useCallback(() => setPlaying(null), []);

  const step = (dir: 1 | -1) => {
    const el = railRef.current;
    el?.scrollBy({ left: dir * el.clientWidth * 0.8, behavior: "smooth" });
  };

  return (
    <section id="film" className="scroll-mt-16 bg-surface py-24 md:py-32">
      <div className="mx-auto flex max-w-350 items-end justify-between gap-6 px-5 md:px-10">
        <h2 className="text-5xl leading-none font-bold tracking-[-0.04em] md:text-7xl">
          On <span className="font-normal italic">film</span>
        </h2>
        <div className="flex gap-2">
          <button type="button" onClick={() => step(-1)} aria-label="Scroll films left" className="flex h-12 w-12 items-center justify-center border border-ink/25 transition-colors hover:border-ink active:scale-95">
            <ArrowLeftIcon size={20} />
          </button>
          <button type="button" onClick={() => step(1)} aria-label="Scroll films right" className="flex h-12 w-12 items-center justify-center border border-ink/25 transition-colors hover:border-ink active:scale-95">
            <ArrowRightIcon size={20} />
          </button>
        </div>
      </div>

      <motion.ul
        ref={railRef}
        className="no-scrollbar mt-12 flex snap-x snap-mandatory gap-4 overflow-x-auto px-5 scroll-px-5 md:gap-6 md:px-10 md:scroll-px-10 xl:px-[max(2.5rem,calc((100vw-1400px)/2+2.5rem))] xl:scroll-px-[max(2.5rem,calc((100vw-1400px)/2+2.5rem))]"
        initial={{ opacity: 0, y: 40 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, amount: 0.2 }}
        transition={{ duration: 0.9, ease: [0.16, 1, 0.3, 1] }}
      >
        {COMMERCIALS.map((c) => (
          <VideoCard
            key={c.id}
            c={c}
            isPlaying={playing === c.id}
            onToggle={() => setPlaying((p) => (p === c.id ? null : c.id))}
            onScrollAway={stop}
          />
        ))}
      </motion.ul>
    </section>
  );
}
